#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fsspec
Version  : 2021.4.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/ab/40/1423275e8b57fb666c0435f9953c681237bf5de3c3eccc0fb208e143e1ce/fsspec-2021.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ab/40/1423275e8b57fb666c0435f9953c681237bf5de3c3eccc0fb208e143e1ce/fsspec-2021.4.0.tar.gz
Summary  : File-system specification
Group    : Development/Tools
License  : BSD-3-Clause
Requires: fsspec-license = %{version}-%{release}
Requires: fsspec-python = %{version}-%{release}
Requires: fsspec-python3 = %{version}-%{release}
Requires: aiohttp
Requires: dask
Requires: distributed
Requires: importlib_metadata
Requires: paramiko
Requires: requests
BuildRequires : aiohttp
BuildRequires : buildreq-distutils3
BuildRequires : dask
BuildRequires : distributed
BuildRequires : paramiko
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : requests
BuildRequires : tox
BuildRequires : virtualenv

%description
# filesystem_spec
[![PyPI version](https://badge.fury.io/py/fsspec.svg)](https://pypi.python.org/pypi/fsspec/)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/fsspec/badges/version.svg)](https://anaconda.org/conda-forge/fsspec)
![Build](https://github.com/intake/filesystem_spec/workflows/CI/badge.svg)
[![Docs](https://readthedocs.org/projects/filesystem-spec/badge/?version=latest)](https://filesystem-spec.readthedocs.io/en/latest/?badge=latest)

%package license
Summary: license components for the fsspec package.
Group: Default

%description license
license components for the fsspec package.


%package python
Summary: python components for the fsspec package.
Group: Default
Requires: fsspec-python3 = %{version}-%{release}

%description python
python components for the fsspec package.


%package python3
Summary: python3 components for the fsspec package.
Group: Default
Requires: python3-core
Provides: pypi(fsspec)

%description python3
python3 components for the fsspec package.


%prep
%setup -q -n fsspec-2021.4.0
cd %{_builddir}/fsspec-2021.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1619707688
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fsspec
cp %{_builddir}/fsspec-2021.4.0/LICENSE %{buildroot}/usr/share/package-licenses/fsspec/05ee6f4bb52a15a0a29b05ceab4c9648092a8c51
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fsspec/05ee6f4bb52a15a0a29b05ceab4c9648092a8c51

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
